//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parcial2_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class userChat
    {
        public int idUser { get; set; }
        public int portUser { get; set; }
        public int idChat { get; set; }
        public int portChat { get; set; }
        public string message { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual User User { get; set; }
    }
}
